#include <expected>
#include <filesystem>
#include <memory>

#include "build.hpp"
#include "components/Command.hpp"
#include "errors.hpp"
#include "sol/state.hpp"
#include "lib/ninja/ninja_syntax.hpp"

namespace cppaper::system {

using entt::registry;
using std::make_unique;

namespace {

auto create_ninja_build(registry &reg) -> std::expected<void, ErrorType> {
  // TODO (yuri): read cppaper.lua file to generate build.ninja
  sol::state lua;
  lua.open_libraries(sol::lib::base, sol::lib::package);
  std::filesystem::path cppaper_lua { "cppaper.lua" };

  if (!std::filesystem::exists(cppaper_lua)) {
    return std::unexpected(ErrorType::kCppaperLuaNotFound);
  }

  if (!std::filesystem::is_regular_file(cppaper_lua)) {
    return std::unexpected(ErrorType::kCppaperIsNotRegularFile);
  }

  lua.script_file(cppaper_lua);

  // TODO (yuri): regenerate only if something changed
  const auto writer =
      ninja_lib::Writer::create(make_unique<std::ofstream>("build.ninja"), 2);

  if (!writer) {
    // TODO(yuri): use expected instead of throwing
    throw std::invalid_argument("Failed to create ninja build file");
  }

  writer->comment("Ninja build file generated by Cppaper");

  writer->rule("pool", std::string_view{ "console" });
  writer->variable("rule", std::string_view{ "cp" });
  writer->variable("command", std::string_view{ "cp $in $out" });

  writer->new_line(1);

  auto site_copy_outputs = std::vector<std::string_view>{
    "site_copy"
  };
  writer->build(site_copy_outputs, std::string_view{ "rule" });

  std::system("ninja -f build.ninja");

  return {};
}
}

auto build_system(entt::registry& registry) -> void {
  auto build_command_view = registry.view<Command, BuildCommand>();

  build_command_view.each([&](auto command_entity) -> void {
    const auto result = create_ninja_build(registry);
  });
}

} // namespace cppaper::system
